var createIntro;

createIntro = require('./intro');

suite('createIntro', function() {
  var diContainerClassName, diContainerFactoryName, requiredNamespaces;
  diContainerFactoryName = null;
  diContainerClassName = null;
  requiredNamespaces = null;
  setup(function() {
    diContainerFactoryName = 'app.diContainer';
    diContainerClassName = 'app.DiContainer';
    return requiredNamespaces = ['Bla', 'Foo'];
  });
  return test('should generate createIntro', function() {
    var src;
    src = createIntro(diContainerFactoryName, diContainerClassName)(requiredNamespaces);
    return assert.equal(src, "// This file was autogenerated by grunt-closure-dicontainer task.\n// Please do not edit.\ngoog.provide('app.diContainer');\n\ngoog.require('goog.Disposable');\ngoog.require('Bla');\ngoog.require('Foo');\n\n/**\n * Factory for app.DiContainer.\n * @param {Object=} config Server side generated app config.\n * @return {app.DiContainer}\n */\napp.diContainer = function(config) {\n  return new app.DiContainer(config);\n};\n\n/**\n * DI container.\n *\n * @param {Object=} config Server side generated app config.\n * @constructor\n * @extends {goog.Disposable}\n */\napp.DiContainer = function(config) {\n  goog.base(this);\n  this.config = config;\n};\ngoog.inherits(app.DiContainer, goog.Disposable);\n\n/**\n * @type {Object}\n */\napp.DiContainer.prototype.config = null;");
  });
});
