module.exports = function(factoryNamespace, classNamespace) {
  var createGoogRequire;
  createGoogRequire = function(namespace) {
    return "goog.require('" + namespace + "');";
  };
  return function(requiredNamespaces) {
    return "// This file was autogenerated by grunt-closure-dicontainer task.\n// Please do not edit.\ngoog.provide('" + factoryNamespace + "');\n\ngoog.require('goog.Disposable');\n" + (requiredNamespaces.map(createGoogRequire).join('\n')) + "\n\n/**\n * Factory for " + classNamespace + ".\n * @param {Object=} config Server side generated app config.\n * @return {" + classNamespace + "}\n */\n" + factoryNamespace + " = function(config) {\n  return new " + classNamespace + "(config);\n};\n\n/**\n * DI container.\n *\n * @param {Object=} config Server side generated app config.\n * @constructor\n * @extends {goog.Disposable}\n */\n" + classNamespace + " = function(config) {\n  goog.base(this);\n  this.config = config;\n};\ngoog.inherits(" + classNamespace + ", goog.Disposable);\n\n/**\n * @type {Object}\n */\n" + classNamespace + ".prototype.config = null;\n";
  };
};
