module.exports = (diContainerName) ->

  createGoogRequire = (namespace) ->
    "goog.require('#{namespace}');"

  (requiredNamespaces) ->
    requiredNamespaces = requiredNamespaces.slice 0
    requiredNamespaces.sort()

    """
      // This file was autogenerated by grunt-closure-dicontainer task.
      // Please do not edit.
      goog.provide('#{diContainerName}');

      #{requiredNamespaces.map(createGoogRequire).join '\n'}

      /**
       * @param {Object=} data Server side data.
       * @constructor
       */
      #{diContainerName} = function(data) {
        if (data)
          this.data = data;
      };

      /**
       * @type {Object}
       */
      #{diContainerName}.prototype.data = null;
    """