module.exports = (diContainerName) ->

  createGoogRequire = (namespace) ->
    "goog.require('#{namespace}');"

  (requiredNamespaces) ->
    requiredNamespaces = requiredNamespaces.slice 0
    requiredNamespaces.sort()

    """
      // This file was autogenerated by grunt-closure-dicontainer task.
      // Please do not edit.
      goog.provide('#{diContainerName}');

      #{requiredNamespaces.map(createGoogRequire).join '\n'}

      /**
       * @constructor
       */
      #{diContainerName} = function() {};
    """