module.exports = function(diContainerFactoryName, diContainerClassName) {
  var createGoogRequire;
  createGoogRequire = function(namespace) {
    return "goog.require('" + namespace + "');";
  };
  return function(requiredNamespaces) {
    return "// This file was autogenerated by grunt-closure-dicontainer task.\n// Please do not edit.\ngoog.provide('" + diContainerFactoryName + "');\n\ngoog.require('goog.Disposable');\n" + (requiredNamespaces.map(createGoogRequire).join('\n')) + "\n\n/**\n * Factory for " + diContainerClassName + ".\n * @param {Object=} config Server side generated app config.\n * @return {" + diContainerClassName + "}\n */\n" + diContainerFactoryName + " = function(config) {\n  return new " + diContainerClassName + "(config);\n};\n\n/**\n * DI container.\n *\n * @param {Object=} config Server side generated app config.\n * @constructor\n * @extends {goog.Disposable}\n */\n" + diContainerClassName + " = function(config) {\n  goog.base(this);\n  this.config = config;\n};\ngoog.inherits(" + diContainerClassName + ", goog.Disposable);\n\n/**\n * @type {Object}\n */\n" + diContainerClassName + ".prototype.config = null;";
  };
};
