// This file was autogenerated by grunt-closure-dicontainer task.
// Please do not edit.
goog.provide('app.diContainer');

goog.require('este.App');
goog.require('este.Router');
goog.require('goog.Disposable');

/**
 * Factory for app.DiContainer.
 * @param {Object=} config Server side generated app config.
 * @return {app.DiContainer}
 */
app.diContainer = function(config) {
  return new app.DiContainer(config);
};

/**
 * DI container.
 *
 * @param {Object=} config Server side generated app config.
 * @constructor
 * @extends {goog.Disposable}
 */
app.DiContainer = function(config) {
  goog.base(this);
  this.config = config;
};
goog.inherits(app.DiContainer, goog.Disposable);

/**
 * @type {Object}
 */
app.DiContainer.prototype.config = null;

/**
 * Factory for este.App.
 * @return {este.App}
 */
app.DiContainer.prototype.esteApp = function() {
  var esteRouter = new este.Router;
  var esteApp = new este.App(esteRouter);
  return esteApp;
};

/**
 * Dispose all instances.
 */
app.DiContainer.prototype.disposeInternal = function() {
  // TODO:
  //  dispose disposable this.types
  //  this.types = null;
  goog.base(this, 'disposeInternal');
};